name: find_camp
description: "Find_Camp"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_storage: ^12.3.7
  firebase_database : ^11.2.0
  file_picker: ^5.2.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.0.0
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  http_parser: ^4.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/Image/
    - assets/Lottie/
